6 small improvements
arpruss/gcodeplot pull request #5
Opened 2018-07-29 21:58 UTC by jrouquie

It's probably more legible to read the commits one by one.

2019-03-21 05:51 UTC, halfluck commented
This is amazing work!  such a nice tidyup. 
The sharpening of the cuttting edge is a great touch but doesn't really work for me as I loose
detail in the cutting edge of the model because of my wall thicknesses 

what I would love to see is a bevel extrude like here ==> 
https://www.thingiverse.com/thing:135408/files
so it creates a nice edge that way.

Thoughts?

Cheers Rob.

2019-03-21 18:43 UTC, arpruss requested changes
Instead of the very time-consuming Minkowski along a ribbon, you should modify ribbon() to do its hull() calls using a different profile than a circle: e.g., a truncated cone on top of a cylinder.

2019-03-22 02:31 UTC, halfluck commented
I've been using the one that improved inside walls, before they were being filled, perhaps you could implement similar? ==>
https://gitlab.com/jimklo/svg2cookiecutter

2019-03-22 05:10 UTC, arpruss approved these changes

2019-03-22 05:10 UTC, merged